若干完成毕设期间做的修改
Shuenhoy/modern-zju-thesis pull request #3
Opened 2024-12-15 10:54 UTC by PepcyCh

硕士论文初稿写完了，来把做的一些修改提过来。各提交的修改内容按时间序如下：

1. 修改了封面的“论文提交日期”部分，使其更长且右端与上面对齐，和 Word 版的示例更像
2. `template-individual` 增加了一个 `indent-first-par` 的参数，给摘要的第一段做缩进
3. `template-individual` 的末尾增加了一个 `twoside-pagebreak`，否则当表目录为奇数页时，页码 1 会出现在表目录最后的偶数页空页上，正文第一页的页码会变成 2
4. 使用 `context` + `here` 修改了 `twoside.typ` 和 `header.typ` 中的部分，代替原来标记了 deprecated 的写法，且原来的写法会导致参考文献部分的页码都出现在右侧，无论实际是奇数页还是偶数页
5. 在 `mainmatter` 中，同样设置段间距为和行间距一样的 1.3em，默认的 1.2em 下能看到正文中两段间的距离比行间距还小一点；加在 `mainmatter` 是防止破坏前面几页的格式
6. 在 `indent-first-par` 中，同样对 list、enum、figure、block equation 做相同的操作，否则也会丢失其下一段的缩进

2024-12-15 11:07 UTC, Shuenhoy commented
感谢贡献！

@ybc3100356 有时间帮忙 review 和测试一下吗？

2024-12-17 07:54 UTC, Shuenhoy requested changes

2024-12-17 07:54 UTC, Shuenhoy commented on utils/indent-first-par.typ
> +  show math.equation.where(block: true): indent-next-par
这样处理有点问题，list, enum 和公式的下面不一定是新的一段。

例如下面的例子，公式(1.1)以句号结尾，而且后续没有别的内容，是段落的结束。但公式(1.2)则是段落的一部分。
![image](https://github.com/user-attachments/assets/5d2c6cff-74f0-4d4c-8eae-571feabcccf2)

论文写作里常见的一种模式`$公式,$ 其中 $a=$, $b=$`就属于第二种情况。

不过 Typst 目前好像区分不了公式后面新段落（有一个空行）和继续段落（无空行）的情况？

2024-12-17 13:27 UTC, PepcyCh commented on utils/indent-first-par.typ
> +  show math.equation.where(block: true): indent-next-par
用 `box` 包起来并不空行可以做到继续段落倒是，但跨页内容不太行。。还是 `h(-2em)` 来的方便些（

类似 https://github.com/flaribbit/indenta 这样的方案做了区别，但放在模板里似乎不太可用（至少我简单试了试不行）

2024-12-18 00:54 UTC, Shuenhoy commented on utils/indent-first-par.typ
> +  show math.equation.where(block: true): indent-next-par
`h(-2em)` (或`h(2em)`) 的缺点是语义化不足，而且如果日后 typst 修复了现在的问题，就会导致少/多缩进了。如果像类似现在我用的`<mzt:no-header-footer>`的标记方法，允许用户在公式等后面加一个`<mzt:continue>`来表示段落未结束你觉得如何？

2024-12-18 03:32 UTC, PepcyCh commented on utils/indent-first-par.typ
> +  show math.equation.where(block: true): indent-next-par
用 `#metadata(<mzt:continue>)` 然后改 `indent-next-par(s)` 为

```typst
let indent-next-par(s) = {
  s
  context {
    if query(metadata.where(value: <mzt:continue>)).filter(el => el.location().position() == here().position()) == () {
      fake-par
    }
  }
}
```

试了下这样可以，无论把 `#metadata(<mzt:continue>)` 加到公式末尾还是下一段开始。套在 `metadata` 里是因为，公式等可能还有自己的一个 label，不能给两个 label。

如果学长觉得这样可以，我就把这个推了？

2024-12-18 03:49 UTC, Shuenhoy commented on utils/indent-first-par.typ
> +  show math.equation.where(block: true): indent-next-par
原来 Typst 不能有两个 label，Typst 确实需要一种类似 CSS 里 class 的东西来方便我们做这些事情。这样的话干脆直接定义一个变量，用的时候写 `#continue`，这样看着自然一些

2024-12-18 04:59 UTC, PepcyCh commented on utils/indent-first-par.typ
> +  show math.equation.where(block: true): indent-next-par
现在用了一个 `continue-par` 表示

2024-12-27 10:36 UTC, ybc3100356 commented
> 感谢贡献！
> 
> @ybc3100356 有时间帮忙 review 和测试一下吗？

lgtm

2024-12-27 10:40 UTC, merged